### ISSUE TITLE
TypeError: Object #<Comments> has no method 'map'

### ISSUE THREAD

**Issue by rwaldron** [bocoup/test262-v8-machinery#12]
``````
$ ./scripts/migrate.sh \
>     v8-git-mirror/test/mjsunit/harmony/arrow-functions.js \
>     test262/test/language/arrow-function/arrow-functions.js

/Users/rwaldron/clonez/test262-v8-machinery/scripts/transform/comments.js:29
    var commentText = ast.program.comments.map(function(node) {
                                           ^
TypeError: Object #<Comments> has no method 'map'
    at makeLicense (/Users/rwaldron/clonez/test262-v8-machinery/scripts/transform/comments.js:29:41)
    at Object.module.exports [as comments] (/Users/rwaldron/clonez/test262-v8-machinery/scripts/transform/comments.js:58:16)
    at module.exports (/Users/rwaldron/clonez/test262-v8-machinery/scripts/transform/index.js:15:13)
    at Object.<anonymous> (/Users/rwaldron/clonez/test262-v8-machinery/scripts/transform.js:35:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
Error: Could not transform v8-git-mirror/test/mjsunit/harmony/arrow-functions.js```
``````

**Comment by rwaldron** [comment]
Updating `recast` corrected this issue.
